# Theme settings
doks:
    baseurl:
    color_theme: blue # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text:
            image: true
        nav:
            - item_name: Github
              item_url: 'https://github.com/marius-team'
    footer:
        content:
            logo:
                text:
                image: true
            copyright: Copyright &copy; 2021. University of Wisconsin-Madison 

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'LICENSE', 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
